# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  local:build:dev:
    desc: Build dev image locally
    aliases:
      - build
    cmds:
      - docker buildx bake -f bake.hcl local

  local:compose:down:
    desc: Remove the local Compose stack
    cmds:
      - docker compose -f local/compose.yaml down

  local:compose:up:
    desc: Create the local Compose stack
    deps:
      - local:compose:down
    aliases:
      - up
    env:
      IMAGE: iut-student-workspace:latest
    cmds:
      - docker compose -f local/compose.yaml up --remove-orphans -d

  local:terminal:
    desc: Open a terminal into the local Compose stack's application container
    aliases:
      - term
    cmds:
      - docker exec -it weather-application /usr/bin/fish
